name: Deploy to CPanel via FTP

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install FTP deployer
      run: |
        sudo apt-get update
        sudo apt-get install lftp

    - name: Deploy to CPanel FTP
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        FTP_TARGET_DIR: ${{ secrets.FTP_TARGET_DIR }}
      run: |
        lftp -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER -e "set ftp:passive-mode on; set ssl:verify-certificate no; mirror -R ./ $FTP_TARGET_DIR; quit"
